name: Publish package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish_npm:
    name: npm publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      deployments: write
    environment:
      name: npm
      url: https://www.npmjs.com/package/model-switchboard

    steps:
      - name: Validate npm token
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if [ -z "$NPM_TOKEN" ]; then
            echo "Error: NPM_TOKEN is not set."
            exit 1
          fi

      - uses: actions/checkout@v6

      - name: Use Node.js 22.x
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: npm
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Publish
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
