name: Scorecard supply-chain security

on:
  branch_protection_rule:
  schedule:
    - cron: "22 4 * * 1"
  push:
    branches:
      - main

permissions: {}

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        # v4.3.1
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false

      - name: Run OpenSSF Scorecard
        # v2.3.3
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload SARIF results to code scanning
        # v3
        uses: github/codeql-action/upload-sarif@7fd177fa680c9881b53cdab4d346d32574c9f7f4
        with:
          sarif_file: results.sarif

      - name: Upload Scorecard artifact
        # v4.6.2
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: scorecard-results
          path: results.sarif
          retention-days: 5
